// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\authn\authenticationvalidator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"
	models "twitter-clone/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuthenticationValidator is a mock of IAuthenticationValidator interface.
type MockIAuthenticationValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthenticationValidatorMockRecorder
}

// MockIAuthenticationValidatorMockRecorder is the mock recorder for MockIAuthenticationValidator.
type MockIAuthenticationValidatorMockRecorder struct {
	mock *MockIAuthenticationValidator
}

// NewMockIAuthenticationValidator creates a new mock instance.
func NewMockIAuthenticationValidator(ctrl *gomock.Controller) *MockIAuthenticationValidator {
	mock := &MockIAuthenticationValidator{ctrl: ctrl}
	mock.recorder = &MockIAuthenticationValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthenticationValidator) EXPECT() *MockIAuthenticationValidatorMockRecorder {
	return m.recorder
}

// ValidateAuthentication mocks base method.
func (m *MockIAuthenticationValidator) ValidateAuthentication(w http.ResponseWriter, r *http.Request) *models.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAuthentication", w, r)
	ret0, _ := ret[0].(*models.User)
	return ret0
}

// ValidateAuthentication indicates an expected call of ValidateAuthentication.
func (mr *MockIAuthenticationValidatorMockRecorder) ValidateAuthentication(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAuthentication", reflect.TypeOf((*MockIAuthenticationValidator)(nil).ValidateAuthentication), w, r)
}
