# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v4

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./compose.yml"

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust version as needed

    - name: Install dependencies
      run: |
        cd e2e_tests
        npm install # Install Node.js dependencies

    - name: Run e2e tests
      run: |
        cd e2e_tests
        npm test # Execute your tests

    - name: Tear down Docker Compose
      if: always() # Ensure it runs even if previous steps fail
      run: docker-compose down
